### ISSUE TITLE
[Feature]: Support for Minecraft 1.20.1

### ISSUE THREAD

**Issue by MarsWonderBoy** [BVengo/anti-entity-grief#1]
### Request Description

Title. 
I'd like to request support for Minecraft version 1.20.1.

**Comment by BVengo** [comment]
Hey, sorry for the late response!
Unfortunately I won't be backdating to previous versions. There are often large changes between major versions, especially in mob behaviour. I don't have heaps of spare time, so primarily just keep up with updates as they come out :)
