### ISSUE TITLE
[Bug]: Trample Egg rule disables capability regardless of setting.

### ISSUE THREAD

**Issue by RubyRezal** [BVengo/anti-entity-grief#2]
### Describe the Bug

Zombie Piglins ignore turtle eggs even when Trample Eggs rule set true.

### Steps to Reproduce

Make sure Trample Eggs rule is true.
Build any gold farm design using turtle eggs as zombie bait, or just place a turtle egg down near zombie piglin. 

### Expected Behavior

Zombie piglins should try to stomp turtle eggs when allowed to by rule.

### Mod Version

1.0.2

**Comment by Aculoss** [comment]
Can confirm.

**Comment by BVengo** [comment]
Thanks for reporting this, quite a serious bug that slipped by me.

Sorry for the late response, just on the tail end of my honeymoon! Will make it a priority as soon as I'm free.
