### ISSUE TITLE
[Bug]: Restarting server resets BREAK_DOORS capability

### ISSUE THREAD

**Issue by Tourmi** [BVengo/anti-entity-grief#4]
### Describe the Bug

When restarting the server, all mobs' BREAK_DOORS capability is reset, and they can break doors again. Running `/entityGriefing minecraft:zombie BREAK_DOORS false` or `/entityGriefingAll BREAK_DOORS false` fixes it until reboot

The config file appears to save the setting properly, however, it does not seem to be loaded properly

Other settings, like EXPLODE_BLOCKS seem to get saved and loaded properly. It is specifically BREAK_DOORS that does not work.

### Steps to Reproduce

* On a server (the issue probably also happens in single player, however, I have not tested it there)
* Run `/entityGriefing minecraft:zombie BREAK_DOORS false`
* Run `/entityGriefing minecraft:zombie BREAK_DOORS`, notice that the setting was set to `false` properly
* Reset the server (`/stop` and restart it)
* Run `/entityGriefing minecraft:zombie BREAK_DOORS`, notice that the setting was reset to `true` after reboot

### Expected Behavior

After restart, it should load the proper values from the `antientitygrief.json` config file

### Fabric Version

Quilt 0.26.3

### Mod Version

1.21-1.0.3

### Log Output

No related logs

**Comment by Tourmi** [comment]
After a bit of looking into the code, seems like the main class loads the config after registering the SERVER_STARTED event, however, since that is just a registration, the code there ends up being run after the rest of onInitialize(), overwriting the config

![image](https://github.com/user-attachments/assets/df83768b-3efd-4e76-b9fa-bf5557ba84d9)

This could be fixed in a few ways, however I don't have a development environment setup, so I can't test these or create a PR 
* Making sure `applyCalculatedCapabilities()` is run before `ConfigParser.loadConfig()`
* Having `EntityCapabilities.with(...)` call `putIfAbsent` instead of `put`, which would avoid overwriting existing values

**Comment by BVengo** [comment]
Dang, thanks for reporting this. Didn't realise I was overwriting existing configs accidentally, so I'll fix that up.
